apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-duckdns
  namespace: default
spec:
  secretName: wildcard-duckdns-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - "*.mnqbox.duckdns.org"